package com.salesmanager.drools.rules;

import com.salesmanager.core.business.modules.integration.shipping.impl.ShippingInputParameters;

global com.salesmanager.core.business.modules.integration.shipping.impl.DecisionResponse decision;

dialect  "mvel"

rule "Shipping custom Quotes Rules"
    when
        ShippingInputParameters(weight > 0)
    then
        decision.setModuleName("customQuotesRules");
end

